name: Test mysql

on:
  push:
    branches:
      - main

jobs:
  setup-wso2-environment:
    runs-on: ubuntu-latest
    env:
      PRODUCT_PACK_NAME : wso2am-3.2.0
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Common Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq
    
    - name: Test MySQL1
      run: |
        # Install MySQL
        sudo apt-get install -y mysql-server
        sudo systemctl start mysql.service
        mysql --version
      continue-on-error: true

    - name: Test MySQL3
      run: |
        mysql --version
        mysql -u root --password=root -e "SHOW DATABASES;"
      continue-on-error: true

    - name: Test MySQL4
      run: |
        sudo mysql --version
        sudo mysql -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpassword';"
        sudo mysql -u root -proot -e "FLUSH PRIVILEGES;"
      continue-on-error: true

    - name: Test MySQL6
      run: |
        mysql --version
        mysql -u root --password=root -e "SHOW DATABASES;"
    
        
        # Create WSO2 databases and user
        sudo mysql -uroot --password=root << EOF
        CREATE DATABASE IF NOT EXISTS WSO2AM_DB CHARACTER SET latin1;
        CREATE DATABASE IF NOT EXISTS WSO2_SHARED_DB CHARACTER SET latin1;
        
        CREATE USER IF NOT EXISTS 'wso2carbon'@'localhost' IDENTIFIED BY 'wso2carbon';
        GRANT ALL PRIVILEGES ON WSO2AM_DB.* TO 'wso2carbon'@'localhost';
        GRANT ALL PRIVILEGES ON WSO2_SHARED_DB.* TO 'wso2carbon'@'localhost';
        FLUSH PRIVILEGES;
        EOF
        
        # Verify MySQL Setup
        mysql -uroot -p${{ github.event.inputs.mysql_root_password }} -e "SHOW DATABASES;"
